target("blank")
    set_kind("phony")
    set_default(false)
    add_deps("libvios")

    on_build(function ()
        os.exec("mkdir -p programs/blank/build assets")
        os.exec("i686-elf-gcc -c -std=gnu99 -ffreestanding -nostdinc -nostdlib -fno-builtin -m32 -fno-pic -fno-pie -fno-stack-protector -g -O0 -Iprograms/stdlib/include programs/blank/blank.c -o programs/blank/build/blank.o")
        os.exec("i686-elf-ld -m elf_i386 -T programs/blank/linker.ld -nostdlib -o assets/blank.elf programs/stdlib/build/start.o programs/blank/build/blank.o assets/libvios.a")
    end)
target_end()
