target("echo")
    set_kind("phony")
    set_default(false)
    add_deps("libvios")

    on_build(function ()
        os.exec("mkdir -p programs/echo/build assets")
        os.exec("i686-elf-gcc -c -std=gnu99 -ffreestanding -nostdinc -nostdlib -fno-builtin -m32 -fno-pic -fno-pie -fno-stack-protector -g -O0 -Iprograms/stdlib/include programs/echo/src/main.c -o programs/echo/build/echo.o")
        os.exec("i686-elf-ld -m elf_i386 -T programs/echo/linker.ld -nostdlib -o assets/echo.elf programs/stdlib/build/start.o programs/echo/build/echo.o assets/libvios.a")
    end)
target_end()
