target("libvios")
    set_kind("phony")
    set_default(false)

    on_build(function ()
        os.exec("mkdir -p programs/stdlib/build assets")
        os.exec("nasm -f elf32 programs/stdlib/src/start.asm -o programs/stdlib/build/start.o")
        os.exec("nasm -f elf32 programs/stdlib/src/vios.asm -o programs/stdlib/build/vios.asm.o")
        os.exec("x86_64-elf-gcc -c -std=gnu99 -ffreestanding -nostdinc -nostdlib -fno-builtin -m32 -fno-pic -fno-pie -fno-stack-protector -g -O0 -Iprograms/stdlib/include programs/stdlib/src/start.c -o programs/stdlib/build/start.c.o")
        os.exec("x86_64-elf-gcc -c -std=gnu99 -ffreestanding -nostdinc -nostdlib -fno-builtin -m32 -fno-pic -fno-pie -fno-stack-protector -g -O0 -Iprograms/stdlib/include programs/stdlib/src/vios.c -o programs/stdlib/build/vios.o")
        os.exec("x86_64-elf-gcc -c -std=gnu99 -ffreestanding -nostdinc -nostdlib -fno-builtin -m32 -fno-pic -fno-pie -fno-stack-protector -g -O0 -Iprograms/stdlib/include programs/stdlib/src/stdlib.c -o programs/stdlib/build/stdlib.o")
        os.exec("x86_64-elf-gcc -c -std=gnu99 -ffreestanding -nostdinc -nostdlib -fno-builtin -m32 -fno-pic -fno-pie -fno-stack-protector -g -O0 -Iprograms/stdlib/include programs/stdlib/src/stdio.c -o programs/stdlib/build/stdio.o")
        os.exec("x86_64-elf-gcc -c -std=gnu99 -ffreestanding -nostdinc -nostdlib -fno-builtin -m32 -fno-pic -fno-pie -fno-stack-protector -g -O0 -Iprograms/stdlib/include programs/stdlib/src/string.c -o programs/stdlib/build/string.o")
    end)
target_end()
